package com.rodrigosambade.mediastoreselected;
import android.app.*; import android.os.*; import android.Manifest; import android.content.*; import android.content.pm.PackageManager; import android.database.Cursor; import android.net.Uri; import android.provider.MediaStore; import android.view.*; import android.widget.*; import java.util.*;
public class MainActivity extends Activity { private TextView out; private static final int REQ=7;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(32,32,32,32);Button p=new Button(this);p.setText("Request library access");p.setOnClickListener(v->requestMedia());l.addView(p);Button q=new Button(this);q.setText("Query visible images");q.setOnClickListener(v->query());l.addView(q);Button pick=new Button(this);pick.setText("System photo picker");pick.setOnClickListener(v->pickOne());l.addView(pick);out=new TextView(this);l.addView(out);setContentView(l);}
 private void requestMedia(){ if(Build.VERSION.SDK_INT>=34)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_IMAGES,Manifest.permission.READ_MEDIA_VIDEO,Manifest.permission.READ_MEDIA_VISUAL_USER_SELECTED},REQ); else if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_IMAGES,Manifest.permission.READ_MEDIA_VIDEO},REQ); else requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},REQ);}
 private void pickOne(){ if(Build.VERSION.SDK_INT>=33)startActivityForResult(new Intent(MediaStore.ACTION_PICK_IMAGES),9); else startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),9); }
 private void query(){String[] pr={MediaStore.Images.Media._ID,MediaStore.Images.Media.DISPLAY_NAME};StringBuilder b=new StringBuilder();int n=0;try(Cursor c=getContentResolver().query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,pr,null,null,MediaStore.Images.Media.DATE_ADDED+" DESC")){if(c!=null)while(c.moveToNext()){n++;if(n<=10)b.append(c.getString(1)).append('\n');}}catch(SecurityException e){b.append("Permission required: ").append(e.getMessage());}out.setText("Visible images: "+n+"\n"+b);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==9&&c==RESULT_OK&&data!=null)out.setText("Picked URI: "+data.getData());}
}
